language: java
jdk: oraclejdk8

addons:
  postgresql: "9.4"

install: mvn clean install -DskipTests -DskipSql -B -V

before_script:
  - psql -c 'create database tastr;' -U postgres
  - mvn initialize -PdbInit -pl tastr-infrastructure -Dtastrenvironment=travis

script: mvn install -B -V -Dtastrenvironment=travis
