language: java
jdk: oraclejdk8

env:
  - DISPLAY=:99.0

addons:
  postgresql: '9.4'

install: mvn clean install -DskipTests -DskipSql -B -V

before_script:
  - psql -c 'create database tastr;' -U postgres
  - mvn initialize -PdbInit -pl tastr-infrastructure -Dtastr.environment=travis
  - sh -e /etc/init.d/xvfb start
script: mvn install -B -V -Dtastr.environment=travis

deploy:
  provider: heroku
  api_key:
    secure: Q0DzNcgSUJpqDvB6/6PP9ZaGDJD/TWiUNxb7eLrWYyJSdbOH4pjzKnebWGU/TjFIIJLWSXqUCDb/7gMWZKH868EpOl+sXhV5g8gOD2E9fjYO2/0+q2Ig1mRMmTsy8eQqRhoyiCdG0V1m2nE/RS93yf98Xf8D3nzd15B7oI7IJf90afUjzKqPrXhENN2p9KaiIdsjY9rY3yXV1XZD2ejPrPEOwd78cqrlyA5pGY3EOI/ETnFcU+XyTbjM80kgk7BELyD6s3mp+1HAC7VqlLdwV5WfnDFwrA9lg65Dzt6yKkN6exzk/LNt50dTbna5EbySn9IzQLpt/I/UnlUeN/VCQnYSGw7yvp5dpP/DvtZl3GAZW9RN6DaiBk44+R+M21Gx9wQZU8LPKqawpSF0Tt04ah0VAnTd/2q/dDdLcqyefGwnHTGxtwo+rXGhn4WItWLf6yh+eCPlY1uCe890kopTutzKVhhhannDVGgkiIcfB/bDioxpZPz+TlLqFj8AFqLZTpbUl/TUCQnchvgjTKGI7dMRij9/xfjfOULW2qo/GSONE+7nt6EL3AnGtbiC2+NyRX9J1sNRTXgmTgGEtp7Upo/WFgOZYi9AkTJX7mMh3zFiOkf83FeohaXI2dTo0/EhTqLHR3jP0s25uQgowLpGio71gXSX+m263+kCTqhRe4U=
  app: tastr
