language: java
jdk: oraclejdk8

env:
  - tastrenvironment=travis

addons:
  postgresql: "9.4"

install: mvn clean install -DskipTests -DskipSql -B -V

before_script:
  - psql -c 'create database tastr;' -U postgres
  - mvn initialize -PdbInit -pl tastr-infrastructure

script: mvn install -B -V
