CREATE ROLE tastr;
ALTER ROLE tastr WITH LOGIN PASSWORD 'tastr' NOSUPERUSER NOCREATEDB NOCREATEROLE;
REVOKE ALL ON DATABASE tastr FROM PUBLIC;
GRANT CONNECT ON DATABASE tastr TO tastr;
GRANT ALL ON DATABASE tastr TO tastr;
